language: java
sudo: required
services:
  - docker
install: true
addons:
  sonarcloud:
    organization: $SONAR_CLOUD_ORGANIZATION
    token: $SONAR_CLOUD_TOKEN
jdk:
  - oraclejdk8
before_install:
  - docker pull sath89/oracle-xe-11g
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
jobs:
  include:
    - stage: compile
      script: mvn clean compile
    - stage: verify
      script: mvn org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar
stages:
  - compile
  - verify